before_script:
  - apt-get update -qq
  - apt-get install -y -qq curl locales
  - echo "en_US UTF-8" > /etc/locale.gen
  - locale-gen en_US.UTF-8
  - export LC_ALL=en_US.UTF-8
  - export PATH=$PATH:/root/.local/bin
  - curl -sSL https://get.haskellstack.org/ | sh

stages:
  - deploy

cache:
  paths:
    - ~/.cabal
    - ~/.ghc
    - ~/.stack

pages:
  stage: deploy
  image: debian:8.6
  script:
    - stack setup
    - stack build
    - stack exec site build
    - mv _site public
  artifacts:
    paths:
    - public
